CREATE DATABASE eauth
GO

USE eauth
GO

CREATE TABLE Users(
Id INT NOT NULL PRIMARY KEY IDENTITY,
UserName VARCHAR(100) NOT NULL,
Email VARCHAR(50) NOT NULL,
PasswordHash TEXT NOT NULL,
PasswordSalt VARCHAR(30) NOT NULL,
IsActive BIT NOT NULL DEFAULT 1,
CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
UpdatedAt DATETIME 
)

CREATE TABLE Roles (
    Id INT NOT NULL PRIMARY KEY IDENTITY,
    Name VARCHAR(50) NOT NULL,
    Description TEXT
);

CREATE TABLE UserRoles (
    UserId INT NOT NULL,
    RoleId INT NOT NULL,
    PRIMARY KEY (UserId, RoleId),
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON DELETE CASCADE
);

CREATE TABLE RefreshTokens (
    Id INT NOT NULL PRIMARY KEY IDENTITY,
    UserId INT NOT NULL,
    Token TEXT NOT NULL,
    Expiration DATETIME NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    RevokedAt DATETIME,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE LoginAttempts (
    Id INT NOT NULL PRIMARY KEY IDENTITY,
    UserName VARCHAR(100),
    IPAddress VARCHAR(50),
    Success BIT NOT NULL,
    AttemptedAt DATETIME NOT NULL DEFAULT GETDATE()
);
